---
title: "Risk metric description"
author: "Team Going Viral"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

The risk metric that forms QQuaVERS depends on multiple data sources. They are currently adapted based on thresholds that will be determined in the main project, and form a linear model. We will detail each datasource and how it is adapted for the metric.

# Rt values

Risk score increases by 1 if the lower 30% credible interval is above 1.

Risk score increases by 2 if the lower 90% credible interval is above 1.

# Forecast

Risk score increases by 1 if mean increase in cases is greater than 100 over the coming week. 

# Vaccination coverage

Risk score increases by 2 if coverage is less than 25%.

Risk score increases by 1 if coverage is less than 50%.

# Sentiment

Risk score increases by 1 if the mean ratio of negative to positive sentiment is greater than 1.

Risk score decreases by 1 if the mean ratio of negative to positive sentiment is less than 1.

